### ISSUE TITLE
Cannot determine a GraphQL host type  (User?) for the "teams" field

### ISSUE THREAD

**Issue by MatrixAge** [xprnio/nestjs-graphql-example#7]
```ts
@Entity('users')
@ObjectType()
export class User {
	@PrimaryGeneratedColumn()
	@Field(() => Int)
	id: number

	@Column()
	@Field({ nullable: false })
	firstName: string

	@Column()
	@Field({ nullable: false })
	lastName: string

	@ManyToMany(() => Team, team => team.members)
	@Field(() => [ Team ], { nullable: true })
	teams: Team[]

	@CreateDateColumn() createdAt: Date

	@UpdateDateColumn() updatedAt: Date
}
```
for 
```ts
	@ManyToMany(() => Team, team => team.members)
	@Field(() => [ Team ], { nullable: true })
	teams: Team[]
```

something wrong with it.I use recently version for all this depencendies.

**Comment by MatrixAge** [comment]
@Entity('users')
@ObjectType()
export class User {
	@PrimaryGeneratedColumn()
	@Field(() => Int)
	id: number

	@Column()
	@Field({ nullable: false })
	firstName: string

	@Column()
	@Field({ nullable: false })
	lastName: string

	@ManyToMany(() => Team, team => team.members)
	@Field(() => [ Team ], { nullable: true })
	teams: Team[]

	@CreateDateColumn() createdAt: Date

	@UpdateDateColumn() updatedAt: Date
}

**Comment by MatrixAge** [comment]
```ts
@Entity('users')
@ObjectType()
@InputType()
export class User {
	@PrimaryGeneratedColumn()
	@Field(() => Int)
	id: number

	@Column()
	@Field({ nullable: false })
	firstName: string

	@Column()
	@Field({ nullable: false })
	lastName: string

	@ManyToMany(() => Team, team => team.members)
	@Field(() => [ Team ], { nullable: true })
	teams: Team[]

	@CreateDateColumn() createdAt: Date

	@UpdateDateColumn() updatedAt: Date
}
```
can be ok.

**Comment by xprnio** [comment]
> ```ts
> @Entity('users')
> @ObjectType()
> @InputType()
> export class User {
> 	@PrimaryGeneratedColumn()
> 	@Field(() => Int)
> 	id: number
> 
> 	@Column()
> 	@Field({ nullable: false })
> 	firstName: string
> 
> 	@Column()
> 	@Field({ nullable: false })
> 	lastName: string
> 
> 	@ManyToMany(() => Team, team => team.members)
> 	@Field(() => [ Team ], { nullable: true })
> 	teams: Team[]
> 
> 	@CreateDateColumn() createdAt: Date
> 
> 	@UpdateDateColumn() updatedAt: Date
> }
> ```
> 
> can be ok.

This isn't really how GraphQL InputTypes and TypeORM's Entities should be used, however. 
The problem here is that since the `id` field is decorated using the `@Field` GraphQL decorator, it will also be settable because it's an InputType, leaving the system error-prone. The preferred method would be to have a separate InputType that only contains the fields that are required from the client when creating a User (meaning the firstName, lastName, and team).

**Comment by xprnio** [comment]
The error was caused because of wrong imports (using `type-graphql` instead of `@nestjs/graphql`).
Those errors were fixed, along with the addition of GraphQL InputType examples, in [`feat/input-types`](https://github.com/xprnio/nestjs-graphql-example/pull/9) which is now merged into `master`
